### ISSUE TITLE
move server to its own repo

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#182]

**Comment by jluethi** [comment]
Have there been thoughts on the general strategy about Fractal repos?
One thing I'd like to maintain: I would like to have a clear main repo to send interested people to, which contains the installation instructions and links to all the relevant parts. This repo doesn't necessarily need to also be the server repo, though I wouldn't aim for too many small repos, because that can get a bit messy.

I could see a scenario where we have:
- Main repo here with installation instructions, links to other repos, examples
- Server & client repo
- Task repo

It does start to get a bit messy though when we have many different repos with different branches. Which server branch will work with which client branch (if they also were to be in different repos) and which task branch? Do we have a good way of managing this? Otherwise, I'd argue for keeping it as compact as possible.

**Comment by jacopo-exact** [comment]
> * Main repo here with installation instructions, links to other repos, examples
> * Server & client repo
> * Task repo

Final expected configuration is:
* fractal: client and common repo
* fractal-server: server component
* fractal-core-tasks: core tasks

the main project repo is the client one, as most end users will only be interested in installing the client and then connect to a remote server.

Interdependencies will be transparent to both client and server users, i.e., `pip install fractal-server` will take care of also installing client and core tasks.

**Comment by jluethi** [comment]
> Final expected configuration is:
> 
> - fractal: client and common repo
> - fractal-server: server component
> - fractal-core-tasks: core tasks

This organisation sounds good to me.

**Comment by jacopo-exact** [comment]
https://github.com/fractal-analytics-platform/fractal-server
