### ISSUE TITLE
add pipy admins and maintainers

### ISSUE THREAD

**Issue by jacopo-exact** [fractal-analytics-platform/fractal#190]
currently @jacopo-exact is the sole owner and maintainer

**Comment by jluethi** [comment]
Would be great if you could give me (user [jluethi](https://pypi.org/user/jluethi/) access as well at some point, so that there would be people both on the exact lab side & on the FMI side with the access, in case it's needed in the future. But I'll leave you (or someone else at Exact lab) in charge of making the actual releases.

**Comment by jacopo-exact** [comment]
As of right now we have both people from exact lab and from fmi on board. I'm closing this issue.
