### ISSUE TITLE
Name uniqueness & ID discussion

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal#267]
We have multiple issues around addressing core tasks by name and fractal enforcing uniqueness for project names & workflow names. Let's use this issue to discuss where we want to have name uniqueness and relax the others.

In my view:
Core tasks need to have unique names and be accessible via their name

We can discuss if projects should have unique names. My intuition would be: For a given users, projects should have unique names, but not for the whole server (i.e. each user can have a `test` project, but no user can have 2 `test` projects). A user could then access any of their projects by name. If we add sharing of projects between users, that would go via ID.

Dataset names should be unique within a project, but not globally and not even for a user (i.e. a user can only have one "Cycle 1" dataset per project, but each project could have a "Cycle 1" dataset).

Workflows can have names and they should be unique for a project. Same as datasets above.

Are there tasks that users would define that should be accessible beyond a project?
1) Custom tasks: We haven't build those yet. Not sure how we would best tackle those.
2) Template workflows: I tend to see those like core tasks, where they should have unique names and be generally accessible to many users. We also haven't implemented that

**Comment by jacopo-exact** [comment]
Implement task cache (kind of similar to what we already do with the token)

- [ ] modify config so as to determine the location of the cache
  * we already have the parameter for the token cache. at this point let's use a whole folder with some files for each cache, e.g., ~/.fractal -> ~/.cache/fractal/ (containing session, task, etc)
- [ ] `get_cached_task_by_name(name: str) -> int`
  * if name in cache, return id
  * if cache miss, refresh cache and repeat
- [ ] whenever `task list` is called, it refreshes the cache as a side effect
- [ ] modify interface so that whenever we ask for a task id, we can use task name instead
  * task edit
  * task add-subtask
  * task apply

**Comment by tcompa** [comment]
To do

- [ ] Add a `clear_task_cache` function, at least as a fixture

**Comment by tcompa** [comment]
To do:
- [ ] update at least a couple of examples

**Comment by tcompa** [comment]
I reopened this issue because it contains more than what #273 solved.

As of #273, the client can call tasks by either IDs or names (both are valid). If the command includes a name, rather than an ID, it is looked up in a local cache file (which maps names to IDs).

The only constraint is the user cannot define a task (e.g. a workflow) with a name which is made only by numbers (e.g. `23432`). A check is in-place for this case.

**Comment by jluethi** [comment]
I think we achieved the main goals behind this issue. If new issues come up, let's open them fresh
